# Generated by Django 4.2.5 on 2023-11-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="code",
            field=models.CharField(default="MEC-1", max_length=10),
        ),
    ]
