# Generated by Django 4.2.5 on 2024-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookquestionfeedback_usersubmittedbookanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquestion',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('math', 'Math')], default='math', max_length=25),
        ),
    ]
